version: '3.1'
services:
  app:
    container_name: app-springboot-postgresql
    image: docker-spring-boot-postgres:latest
    build: ../../../..
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres:latest
    container_name: dbpostgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgrest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ninja
